project:
  type: website

website:
  title: "Intelligence and Education"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: plot2.qmd
        text: Plot 2
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



